"use client";
import React, { useState, useEffect } from 'react';
import useSWR from 'swr';
import { Plus, Search, X } from 'lucide-react';
import { motion } from 'framer-motion';

const fetcher = (u:string)=>fetch(u).then(r=>r.json());
interface Revenue { id?:number; source:string; amount:number; period_start:string|null; period_end:string|null; created_at?:string; }
interface RevResponse { items:Revenue[]; total:number; page:number; pages:number; pageSize:number; }

export default function RevenuePage(){
  const [page,setPage]=useState(1); const [pageSize]=useState(10); const [q,setQ]=useState('');
  const [showForm,setShowForm]=useState(false); const [form,setForm]=useState<Revenue>({ source:'', amount:0, period_start:'', period_end:'' });
  const query='/api/revenue?page='+page+'&pageSize='+pageSize+'&q='+encodeURIComponent(q);
  const { data, mutate, isLoading } = useSWR<RevResponse>(query, fetcher, { refreshInterval:8000 });
  useEffect(()=>{ setPage(1); },[q]);
  const submit=async(e:React.FormEvent)=>{ e.preventDefault(); await fetch('/api/revenue',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form, amount:Number(form.amount), period_start:form.period_start||null, period_end:form.period_end||null})}); setShowForm(false); setForm({ source:'', amount:0, period_start:'', period_end:'' }); mutate(); };

  return (
    <div className="py-40 my-10 md:px-24 p-6 md:py-20 min-h-screen bg-gradient-to-br from-gray-50 to-blue-100 dark:from-gray-950 dark:via-blue-950 dark:to-purple-950 text-gray-900 dark:text-white">
      <h1 className="text-3xl font-bold mb-6 bg-gradient-to-r from-fuchsia-600 via-purple-600 to-indigo-600 text-transparent bg-clip-text">Finance / Revenue</h1>
      <div className="flex flex-col lg:flex-row gap-4 items-stretch lg:items-center mb-8 p-4 rounded-2xl bg-white/60 dark:bg-gray-900/50 backdrop-blur border border-white/40 dark:border-gray-700">
        <div className="flex-1 flex items-center gap-3 bg-white/70 dark:bg-gray-800/70 rounded-xl px-4 py-2.5 border border-gray-200/60 dark:border-gray-700/70"><Search size={18} className="text-fuchsia-600"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search source" className="bg-transparent w-full outline-none text-sm"/></div>
        <button onClick={()=>setShowForm(true)} className="px-6 py-2.5 rounded-xl font-medium text-white bg-gradient-to-r from-fuchsia-600 via-purple-600 to-indigo-600 shadow-lg hover:brightness-110 flex items-center gap-2"><Plus size={16}/>New Revenue</button>
      </div>
      <div className="overflow-hidden rounded-2xl bg-white/70 dark:bg-gray-900/60 backdrop-blur border border-gray-200 dark:border-gray-700 shadow-xl">
        <div className="overflow-auto"><table className="w-full text-sm"><thead><tr className="bg-gray-100 dark:bg-gray-800"><th className="px-4 py-3 text-left">Source</th><th className="px-4 py-3 text-left">Amount</th><th className="px-4 py-3 text-left">Period</th><th className="px-4 py-3 text-left">Created</th></tr></thead><tbody>{isLoading && <tr><td colSpan={4} className="py-10 text-center">Loading...</td></tr>}{data?.items?.length===0 && !isLoading && <tr><td colSpan={4} className="py-10 text-center">No revenue entries.</td></tr>}{data?.items?.map(r=> <tr key={r.id} className="border-t border-gray-200 dark:border-gray-700 hover:bg-fuchsia-50 dark:hover:bg-gray-800/70"><td className="px-4 py-3 font-medium">{r.source}</td><td className="px-4 py-3 font-mono">${Number(r.amount).toLocaleString()}</td><td className="px-4 py-3">{r.period_start? new Date(r.period_start).toLocaleDateString():''} {r.period_end? ' - '+new Date(r.period_end).toLocaleDateString():''}</td><td className="px-4 py-3">{r.created_at? new Date(r.created_at).toLocaleDateString():''}</td></tr>)}</tbody></table></div>
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 px-4 py-4 border-t border-gray-200 dark:border-gray-700 bg-gray-50/70 dark:bg-gray-800/40"><span className="text-xs md:text-sm text-gray-600 dark:text-gray-400">Page {data?.page||1} of {data?.pages||1} • {data?.total||0} total</span><div className="flex gap-2"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)} className="px-4 py-1.5 rounded-full bg-gray-200 dark:bg-gray-700 disabled:opacity-40 text-sm">Prev</button><button disabled={page>=(data?.pages||1)} onClick={()=>setPage(p=>p+1)} className="px-4 py-1.5 rounded-full bg-gray-200 dark:bg-gray-700 disabled:opacity-40 text-sm">Next</button></div></div>
      </div>
      {showForm && (<div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm"><motion.div initial={{y:40,opacity:0}} animate={{y:0,opacity:1}} className="w-full max-w-lg bg-white dark:bg-gray-900 rounded-2xl p-8 shadow-2xl border border-gray-200 dark:border-gray-700 relative"><button onClick={()=>setShowForm(false)} className="absolute top-3 right-3 p-2 rounded-full hover:bg-gray-100 dark:hover:bg-gray-800"><X size={16}/></button><h2 className="text-2xl font-bold mb-6 bg-gradient-to-r from-fuchsia-600 via-purple-600 to-indigo-600 text-transparent bg-clip-text">New Revenue</h2><form onSubmit={submit} className="space-y-5"><div><label className="block text-xs font-semibold mb-1">Source</label><input required value={form.source} onChange={e=>setForm({...form,source:e.target.value})} className="w-full rounded-xl bg-gray-100 dark:bg-gray-800 px-4 py-2.5 outline-none"/></div><div className="grid grid-cols-1 md:grid-cols-2 gap-5"><div><label className="block text-xs font-semibold mb-1">Amount</label><input type="number" value={form.amount} onChange={e=>setForm({...form,amount:parseFloat(e.target.value||'0')})} className="w-full rounded-xl bg-gray-100 dark:bg-gray-800 px-4 py-2.5 outline-none"/></div></div><div className="grid grid-cols-1 md:grid-cols-2 gap-5"><div><label className="block text-xs font-semibold mb-1">Period Start</label><input type="date" value={form.period_start||''} onChange={e=>setForm({...form,period_start:e.target.value})} className="w-full rounded-xl bg-gray-100 dark:bg-gray-800 px-4 py-2.5 outline-none"/></div><div><label className="block text-xs font-semibold mb-1">Period End</label><input type="date" value={form.period_end||''} onChange={e=>setForm({...form,period_end:e.target.value})} className="w-full rounded-xl bg-gray-100 dark:bg-gray-800 px-4 py-2.5 outline-none"/></div></div><div className="flex justify-end gap-3 pt-2"><button type="button" onClick={()=>setShowForm(false)} className="px-5 py-2.5 rounded-xl bg-gray-200 dark:bg-gray-700 text-sm font-medium">Cancel</button><button type="submit" className="px-5 py-2.5 rounded-xl bg-gradient-to-r from-fuchsia-600 via-purple-600 to-indigo-600 text-white text-sm font-semibold shadow-lg">Create</button></div></form></motion.div></div>)}
    </div>
  );
}
