"use client"
import React from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Sidebar from "../components/Sidebar";
import MobileMenu from "../components/MobileMenu";
import Footer from "../components/Footer";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = typeof window !== "undefined" ? window.location.pathname : "";
  const isAuthPage = pathname.startsWith("/auth");

  return (
    <html lang="en">
      <body className="antialiased bg-gradient-to-br from-gray-950 to-gray-900 text-white min-h-screen">
        {!isAuthPage && <Navbar />}
        <div className="flex">
          {!isAuthPage && <Sidebar />}
          <main className="flex-1">{children}</main>
        </div>
        {!isAuthPage && <MobileMenu />}
        {!isAuthPage && <Footer />}
      </body>
    </html>
  );
}
